import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const fbpung = localFont({
  src:"../../public/fonts/FB-pung-pop-M.ttf",
  display: "swap",
  variable: "--font-fbpung"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fbpung.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
